### ISSUE TITLE
collectstatic

### ISSUE THREAD

**Issue by denk1** [archatas/django_docker#3]
Hello,
Could you tell me why I get such an error while I run:
**python manage.py collectstatic**
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/myproject/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/myproject/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/myproject/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/myproject/env/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/myproject/env/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/home/myproject/env/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 113, in collect
    handler(path, prefixed_path, storage)
  File "/home/myproject/env/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 348, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/home/myproject/env/lib/python3.8/site-packages/django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "/home/myproject/env/lib/python3.8/site-packages/django/core/files/storage.py", line 248, in _save
    os.makedirs(directory, exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/myproject/static/site'

I have root permissions on the volumes

**Comment by denk1** [comment]
I have resolved by running root

**Comment by citmusa** [comment]
Before creating the volumes, create the static and media folders that are missing in this repo:
```
mkdir -p src/myproject/media
mkdir -p src/myproject/static
```

Another option is to ssh as root and change the permissions:
```
docker exec -u 0 -it django_docker_gunicorn_1 bash
chown -R myproject static
chown -R myproject media
```

From now on you can continue using just myproject user privileges
